---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns-openshift-cluster-observability-operator.yaml
- og-openshift-cluster-observability-operator.yaml
- sub-cluster-observability-operator.yaml
- uiplugin-logging.yaml
- uiplugin-distributed-tracing.yaml
- uiplugin-monitoring.yaml
- uiplugin-troubleshooting-panel.yaml
